pms_finance_dashboard:
    path:     /
    defaults: { _controller: PmsFinanceBundle:Dashboard:index }
pms_finance_importer:
    path: /importer
    defaults: { _controller: PmsFinanceBundle:Importer:index }
pms_finance_transaction_save:
    path:     /api/transaction/save
    defaults: { _controller: PmsFinanceBundle:Transaction:apiSave }
    options:
        expose: true
pms_finance_transaction_form_data:
    path:     /api/transaction/form-data
    defaults: { _controller: PmsFinanceBundle:Transaction:apiFormData }
    options:
        expose: true
pms_finance_balance_data:
    path:     /api/balance/data
    defaults: { _controller: PmsFinanceBundle:Dashboard:apiBalanceData }
    options:
        expose: true
