pms_finance_dashboard:
    path:     /
    defaults: { _controller: PmsFinanceBundle:Dashboard:index }
pms_finance_importer:
    path: /importer
    defaults: { _controller: PmsFinanceBundle:Importer:index }
pms_finance_async_save_transaction:
    path:     /async/save-transaction
    defaults: { _controller: PmsFinanceBundle:Dashboard:saveTransaction }
    options:
        expose: true

