pms_finance_dashboard:
    path:     /
    defaults: { _controller: PmsFinanceBundle:Dashboard:index }
pms_finance_importer:
    path: /importer
    defaults: { _controller: PmsFinanceBundle:Importer:index }
pms_finance_dummy:
    path:     /dummy
    defaults: { _controller: PmsFinanceBundle:Dashboard:dummy }
    options:
        expose: true

