pms_finance_dashboard:
    path:     /
    defaults: { _controller: PmsFinanceBundle:Dashboard:index }
pms_finance_importer:
    path: /importer
    defaults: { _controller: PmsFinanceBundle:Importer:index }
pms_finance_save_transaction:
    path:     /api/transaction/save
    defaults: { _controller: PmsFinanceBundle:Transaction:apiSave }
    options:
        expose: true

