services:
    pms_finance.menu:
        class: Pms\FinanceBundle\Service\MenuService
        arguments: []
    pms_finance.transaction:
        class: Pms\FinanceBundle\Service\TransactionService
        arguments:
            em: "@doctrine.orm.entity_manager"
    pms_finance.history:
        class: Pms\FinanceBundle\Service\HistoryService
        arguments:
            em: "@doctrine.orm.entity_manager"

